language: node_js
node_js:
  - 14
install:
  - npm install plotly.js-dist
  - npm install mocha -g
  - npm install codecov -g
script:
- npm run tests/general.js
- npm run report-coverage
after_script:
  - cov